# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for the "master" and "develop" branches
  pull_request:
    branches: [ "master", "develop" ]
    types: [ opened, edited, reopened, synchronize, ready_for_review, unlocked, auto_merge_enabled]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "pr-sanity-checks"
  pr-sanity-checks:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Run each check
      - name: Check if a branch other than develop is being merged to master
        shell: bash
        run: if [ $GITHUB_HEAD_REF != "develop" ] && [ $GITHUB_BASE_REF = "master" ]; then echo "::error No branch other than develop can be merged to master. Your base branch is $GITHUB_BASE_REF and head branch is $GITHUB_HEAD_REF" && exit 1; else echo "::notice check successful"; fi

      - name: Check if a branch master is being merged to any other branch
        shell: bash
        run: if [ $GITHUB_HEAD_REF = "master" ]; then echo "::error Master branch cannot be merged to any other branch." && exit 1; else echo "::notice check successful" ; fi
